=== solargis/schemas/solargis_public_TMY_API_pilot_request.schema.json
{
  "$id": "https://raw.githubusercontent.com/solargis/schemas/v1.1.7/solargis_public_TMY_API_pilot_request.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",

  "description": "Schema for public Solargis data request - for TMY API pilot version.",
  "required": [
    "latitude",
    "longitude",
    "timeStep",
    "outputFormats",
    "tmyScenario"
  ],
  "properties": {
    "latitude": {
      "description": "Latitude coordinate in decimal format [-90,90]",
      "type": "number",
      "minimum": -90,
      "maximum": 90
    },
    "longitude": {
      "description": "Longitude coordinate in decimal format [-180,180]",
      "type": "number",
      "minimum": -180,
      "maximum": 180
    },
    "timeStep": {
      "type": "string",
      "enum": [
        "PT15M",
        "PT60M"
      ]
    },
    "tmyScenario": {
      "type": "string",
      "const": "P50"
    },
    "outputFormats": {
      "type": "array",
      "uniqueItems": true,
      "minItems": 1,
      "items": {
        "type": "string",
        "enum": [
          "SOLARGIS_JSON",
          "SOLARGIS_CSV",
          "SAM",
          "HELIOSCOPE",
          "SOLARGIS_PARQUET"
        ]
      }
    },
    "fileLabel": {
      "description": "User provided label used for file name generation only",
      "type": "string",
      "maxLength": 10,
      "pattern": "^\\w*$"

    },
    "siteName": {
      "description": "User provided value",
      "type": "string",
      "maxLength": 50,
      "pattern": "^\\S.*$"

    }
  }
}

=== solargis/schemas/v1.0/examples/requests/public/tmy_api_pilot_request.json
{
  "$schema": "https://raw.githubusercontent.com/solargis/schemas/main/v1.0/solargis_public_TMY_API_pilot_request.schema.json",
  "latitude": 45,
  "longitude": 17,
  "timeStep": "PT15M",
  "tmyScenario": "P50",
  "outputFormats": [
    "SOLARGIS_JSON",
    "SOLARGIS_CSV"
  ],
  "siteName": "bbb"

}
